version: '3.8'
services:
  ba-modding-toolkit-web:
    build:
      context: .
      args:
        GIT_TAG: ${GIT_TAG:-}
        GIT_COMMIT: ${GIT_COMMIT:-}
    image: jacksen168/ba-modding-toolkit-web:latest
    container_name: ba-modding-toolkit-web
    network_mode: bridge
    ports:
      - "8200:80"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/bamt.db
      - DEBUG=false
    restart: unless-stopped
